-- ==========================================
-- Migration 021: Update old seed scenario descriptions
-- Makes all remaining short descriptions detailed (100-200 words)
-- Covers 23 scenarios from earlier migrations
-- ==========================================

-- 1. outdoor-bbq-birthday
UPDATE public.scenarios SET
  description_tr = 'Bahçede mangal doğum günü partisi, sıcak bir atmosferde sevdiklerinizi bir araya getirmenin en güzel yoludur. Bir hafta öncesinden davetiye gönderin ve misafir sayısını netleştirin. Et, tavuk, sebze ve özel soslar için alışveriş listesi hazırlayın; vejetaryen konuklarınız için halloumi peyniri ve mantar şiş alternatifleri ekleyin. Bahçeyi renkli ışık zincirleri, balonlar ve masa örtüleriyle süsleyin — doğum günü kişisinin favori renklerini kullanın. Mangalı partiden en az bir saat önce yakın, közlerin hazır olması zaman alır. Bir köşeye içecek masası kurun: limonata, meyveli su, soğuk çay. Bluetooth hoparlörle neşeli bir playlist çalın. Pastayı sürpriz olarak saklayın; hava karardığında mumları yakıp hep birlikte şarkı söyleyin. Misafirlerden önceden kısa video mesajlar toplayın ve bunları bir tablette oynatın. Sivrisinek kovucu ve güneş kremi bulundurmayı unutmayın. Çocuklar varsa bahçe oyunları hazırlayın: su tabancası, hazine avı veya ip atlama. Her misafire küçük bir teşekkür hediyesi verin — ev yapımı kurabiye veya mini reçel kavanozları harika olur.',
  description_en = 'An outdoor BBQ birthday party is the best way to bring your loved ones together in a warm atmosphere. Send invitations a week in advance and confirm the guest count. Prepare a shopping list for meat, chicken, vegetables, and special sauces; add halloumi cheese and mushroom skewer alternatives for vegetarian guests. Decorate the garden with colorful string lights, balloons, and tablecloths — use the birthday person''s favorite colors. Light the grill at least an hour before the party, as the coals need time to be ready. Set up a beverage station in one corner: lemonade, fruit-infused water, iced tea. Play an upbeat playlist on a Bluetooth speaker. Keep the cake hidden as a surprise; when it gets dark, light the candles and sing together. Collect short video messages from guests beforehand and play them on a tablet. Don''t forget mosquito repellent and sunscreen. If children are attending, prepare garden games: water guns, treasure hunts, or jump rope. Give each guest a small thank-you gift — homemade cookies or mini jam jars work wonderfully.'
WHERE slug = 'outdoor-bbq-birthday';

-- 2. graduation-surprise-party
UPDATE public.scenarios SET
  description_tr = 'Mezuniyet sürpriz partisi, yıllarca süren emeğin ve başarının kutlanmayı hak ettiği özel bir andır. Öncelikle mezun olan kişinin en yakın arkadaşlarını ve ailesini gizlice organize edin; bir WhatsApp grubu kurup planı paylaşın. Mekanı seçin: ev, restoran veya kiralık bir alan olabilir. Mezuniyet temalı süslemeler hazırlayın — diplomalı balonlar, ''Tebrikler Mezun!'' pankartı, okul renkleri. Fotoğraf köşesi kurun: kep, diploma rulosu ve komik tabelalar yerleştirin. Bir slayt gösterisi hazırlayın: bebeklikten mezuniyete kadar kronolojik fotoğraflar ve öğretmenlerden, arkadaşlardan toplanan tebrik mesajları. Mezunu eve veya mekana getirmek için inandırıcı bir bahane uydurun — ''aile yemeği'' veya ''eşya taşıma yardımı'' gibi. Herkes karanlıkta saklanıp kapı açıldığında ''Sürpriz!'' diye bağırsın. Konfeti patlatın ve müziği açın. Pasta üzerine ''Artık gerçek dünyaya hoş geldin!'' gibi esprili bir yazı yazdırın. Konuşma sırası verin: herkes kısa ve anlamlı bir tebrik mesajı söylesin. Mezuna, içinde herkesin yazdığı mektupların olduğu bir hatıra kutusu hediye edin — yıllar sonra bile gözyaşıyla okuyacağı anılar.',
  description_en = 'A graduation surprise party is a special moment because years of hard work and achievement deserve to be celebrated. First, secretly organize the graduate''s closest friends and family; create a WhatsApp group and share the plan. Choose the venue: it could be a home, restaurant, or rented space. Prepare graduation-themed decorations — diploma balloons, a ''Congratulations Graduate!'' banner, school colors. Set up a photo booth with caps, diploma rolls, and funny signs. Create a slideshow: chronological photos from babyhood to graduation, plus congratulatory messages from teachers and friends. Come up with a convincing excuse to bring the graduate to the venue — like a ''family dinner'' or ''help me move stuff.'' Have everyone hide in the dark and shout ''Surprise!'' when the door opens. Pop confetti and turn on the music. Get a cake with a humorous message like ''Welcome to the real world!'' Give everyone a turn to share a short, meaningful congratulatory message. Gift the graduate a memory box filled with letters written by everyone — memories they will read with tears even years later.'
WHERE slug = 'graduation-surprise-party';

-- 3. classic-baby-shower
UPDATE public.scenarios SET
  description_tr = 'Klasik baby shower, yeni gelecek bebeği ve anne adayını kutlamanın en tatlı yoludur. İki hafta öncesinden hazırlığa başlayın: cinsiyet belli ise pembe veya mavi, belli değilse sarı ve yeşil tonlarında dekorasyon seçin. Balonlar, kağıt çiçekler ve ''Hoş geldin bebek'' yazılı bir pankart hazırlayın. Bir hediye masası kurun ve misafirlerden bebek bezi, tulumlar veya oyuncak getirmelerini isteyin. Oyunlar planlayın: ''Biberondaki şeker sayısını tahmin et'', ''Bebek fotoğrafı eşleştirme'' veya ''Bebek kelimesi yasaklı konuşma'' klasik favorilerdir. Bir dilek ağacı hazırlayın: küçük kartlara herkes bebeğe bir dilek yazsın ve ağaca assın. İkram masasına pastel renkli kurabiyeler, mini sandviçler, meyve tabağı ve tatlı bir pasta koyun — pastanın üzerine bebek ayağı veya kundak figürü çok şirin durur. Anne adayı için rahat bir ''onur koltuğu'' süsleyin. Her misafire küçük bir hatıra hediyesi verin: lavanta kesesi, mini mum veya bebek temalı anahtar askısı. En önemlisi, anne adayına ne kadar sevildiğini hissettirin — bu gün tamamen onun için.',
  description_en = 'A classic baby shower is the sweetest way to celebrate the new baby and the mom-to-be. Start preparing two weeks in advance: choose pink or blue decorations if the gender is known, or yellow and green tones if not. Prepare balloons, paper flowers, and a ''Welcome Baby'' banner. Set up a gift table and ask guests to bring diapers, onesies, or toys. Plan games: ''Guess the number of candies in the bottle,'' ''Match the baby photo,'' or ''No saying the word baby'' are classic favorites. Create a wish tree: have everyone write a wish for the baby on small cards and hang them on the tree. On the refreshment table, place pastel-colored cookies, mini sandwiches, a fruit platter, and a sweet cake — baby feet or swaddle figures on the cake look adorable. Decorate a comfortable ''honor seat'' for the mom-to-be. Give each guest a small party favor: a lavender sachet, mini candle, or baby-themed keychain. Most importantly, make the mom-to-be feel how loved she is — this day is entirely for her.'
WHERE slug = 'classic-baby-shower';

-- 4. movie-marathon-night
UPDATE public.scenarios SET
  description_tr = 'Film maratonu gecesi, arkadaşlarla veya sevgilinizle unutulmaz bir akşam geçirmenin en keyifli yollarından biridir. Öncelikle bir tema seçin: korku filmleri, 90''lar klasikleri, Marvel serisi veya Studio Ghibli gibi. Üç ile beş film belirleyin ve sıralamayı önceden planlayın — en hafifinden en ağırına doğru gitmek iyi bir stratejidir. Salonu sinema atmosferine dönüştürün: perdeleri kapatın, yere yumuşak yastıklar ve battaniyeler serin, ışıkları kısın veya LED şerit ışık kullanın. Atıştırmalık masası kurun: patlamış mısır (tereyağlı ve karamelli), nachos, pizza dilimleri, çikolatalı fondue ve içecekler. Her film arasında on dakikalık mola verin — tuvalet, germe ve tartışma zamanı. Film değerlendirme kartları hazırlayın: herkes izlediği filme 1-10 arası puan versin. Rahat kıyafetler giyin, telefonları sessiz moda alın. Gecenin sonunda ''en iyi film'' oylaması yapın. Kış geceleriyse sıcak çikolata, yaz geceleriyse buzlu içecekler tercih edin. Komşulara gürültü konusunda önceden bilgi verin — özellikle korku filmi çığlıkları için!',
  description_en = 'A movie marathon night is one of the most enjoyable ways to spend an unforgettable evening with friends or your partner. First, choose a theme: horror movies, 90s classics, the Marvel series, or Studio Ghibli. Select three to five films and plan the order in advance — going from lightest to heaviest is a good strategy. Transform the living room into a cinema atmosphere: close the curtains, lay soft pillows and blankets on the floor, dim the lights or use LED strip lighting. Set up a snack station: popcorn (buttered and caramel), nachos, pizza slices, chocolate fondue, and drinks. Take a ten-minute break between each film — time for restroom, stretching, and discussion. Prepare movie rating cards: everyone scores each film from 1 to 10. Wear comfortable clothes and put phones on silent mode. At the end of the night, hold a ''best movie'' vote. For winter nights choose hot chocolate, for summer nights choose iced drinks. Give neighbors a heads-up about noise — especially for horror movie screams!'
WHERE slug = 'movie-marathon-night';

-- 5. home-spa-date
UPDATE public.scenarios SET
  description_tr = 'Evde spa gecesi, günlük stresin ardından partnerinizle birlikte rahatlayıp bağınızı güçlendirmenin harika bir yoludur. Banyoyu ve yatak odasını önceden hazırlayın: lavanta veya okaliptüs kokulu mumlar yakın, ışıkları kısın, sakinleştirici doğa sesleri veya lo-fi müzik çalın. Havlu rulolarını şık bir şekilde katlayın ve güzel kokulu sabunlar dizin. Yüz maskesi çeşitleri hazırlayın: nemlendirici, arındırıcı ve besleyici. Evde yapılabilecek peeling karışımı hazırlayın: zeytinyağı, kahve telvesi ve bal karışımı mükemmeldir. Sıcak suyla ayak banyosu hazırlayın, içine birkaç damla uçucu yağ ekleyin. El ve ayak masajı için nemlendirici bir losyon bulundurun — YouTube''dan basit masaj tekniklerini önceden öğrenin. Küçük salatalık dilimleri göz maskesi olarak kullanın. İkram olarak detoks suyu (limon, salatalık, nane), meyve tabağı ve bitter çikolata hazırlayın. Bornoz ve terlik giyin, telefonları başka odada bırakın. Bu gece tamamen birbirinize odaklanma gecesi — dertleri konuşmak yok, sadece rahatlama ve keyif. Gecenin sonunda birlikte yıldızlara bakarak bitirin.',
  description_en = 'A home spa date is a wonderful way to relax and strengthen your bond with your partner after daily stress. Prepare the bathroom and bedroom in advance: light lavender or eucalyptus-scented candles, dim the lights, and play calming nature sounds or lo-fi music. Roll towels elegantly and arrange nicely scented soaps. Prepare face mask varieties: moisturizing, purifying, and nourishing. Make a homemade scrub: a mix of olive oil, coffee grounds, and honey works perfectly. Prepare a warm foot bath and add a few drops of essential oil. Have a moisturizing lotion for hand and foot massages — learn simple massage techniques from YouTube beforehand. Use small cucumber slices as eye masks. For refreshments, prepare detox water (lemon, cucumber, mint), a fruit platter, and dark chocolate. Wear robes and slippers, and leave phones in another room. This night is all about focusing on each other — no talking about worries, just relaxation and enjoyment. End the evening by watching the stars together.'
WHERE slug = 'home-spa-date';

-- 6. escape-room-adventure
UPDATE public.scenarios SET
  description_tr = 'Kaçış odası macerası, arkadaş grubunuz veya partnerinizle birlikte adrenalin dolu bir deneyim yaşamanızı sağlar. Öncelikle şehrinizde iyi puan almış kaçış odalarını araştırın; zorluk seviyesini grubunuzun deneyimine göre seçin — ilk kez deneyenlerse orta seviye ideal. En az bir hafta öncesinden rezervasyon yapın, hafta sonları hızla dolar. Grubunuzu dört ile altı kişi arasında tutun, çok kalabalık gruplar karar vermekte zorlanır. Öncesinde rahat kıyafetler giyin ve değerli eşyaları araçta bırakın. Odaya girince panik yapmayın: ilk beş dakikayı ortamı taramak için kullanın. Görev dağılımı yapın — biri ipuçlarını toplar, biri kilitleri dener, biri büyük resmi görür. İletişim çok önemlidir, bulduğunuz her ipucunu sesli paylaşın. Takılırsanız ipucu kullanmaktan çekinmeyin, eğlence önemli. Çıkışta grup fotoğrafı çektirin ve zamanınızı paylaşın. Sonrasında yakın bir kafede deneyimi konuşarak kutlayın. Özel günler için bazı odalar sürpriz paketleri sunar — doğum günü pastası veya teklif anı gibi. Bu deneyim ekip çalışmasını güçlendirir ve unutulmaz anılar bırakır.',
  description_en = 'An escape room adventure provides an adrenaline-filled experience with your friend group or partner. First, research well-rated escape rooms in your city; choose the difficulty level based on your group''s experience — medium difficulty is ideal for first-timers. Book at least a week in advance as weekends fill up fast. Keep your group between four and six people; overly large groups struggle with decision-making. Wear comfortable clothing beforehand and leave valuables in the car. When you enter the room, don''t panic: use the first five minutes to scan the environment. Assign roles — one person collects clues, one tests locks, one sees the big picture. Communication is crucial; share every clue you find out loud. Don''t hesitate to use hints if you get stuck — the fun is what matters. Take a group photo at the exit and share your completion time. Afterwards, celebrate and discuss the experience at a nearby cafe. For special occasions, some rooms offer surprise packages — like a birthday cake or proposal moment. This experience strengthens teamwork and leaves unforgettable memories.'
WHERE slug = 'escape-room-adventure';

-- 7. friendship-appreciation-day
UPDATE public.scenarios SET
  description_tr = 'Arkadaşlık takdir günü, hayatınızdaki değerli dostlukları kutlamanın ve arkadaşlarınıza ne kadar önemli olduklarını hatırlatmanın güzel bir yoludur. Bir tarih belirleyin ve arkadaşlarınızı bir araya getirin — ev yemeği, piknik veya brunch olabilir. Her arkadaşınız için kişiselleştirilmiş bir mektup yazın: tanıştığınız anı, birlikte yaşadığınız komik olayları ve onların hayatınıza kattığı değeri anlatın. Bu mektupları güzel zarflara koyun ve isimlerini üstüne yazın. Birlikte eski fotoğraflara bakın, anıları canlandırın. ''En iyi an'' oyunu oynayın: herkes grubun en güzel anısını anlatsın. Birbiriniz için küçük ama anlamlı hediyeler hazırlayın — bütçe sınırı koyun ki kimse baskı hissetmesin. Bir dostluk kapsülü yapın: bir kavanoza herkes bir dilek ve bir anı yazsın, bir yıl sonra açmak üzere mühürleyin. Grup fotoğrafı çekip çerçevelettirin. Bu günü yıllık gelenek haline getirin. Unutmayın, arkadaşlık bakım ister — bu özel gün, o bakımın en güzel ifadesidir.',
  description_en = 'A friendship appreciation day is a beautiful way to celebrate the valuable friendships in your life and remind your friends how important they are. Set a date and bring your friends together — it could be a home-cooked meal, picnic, or brunch. Write a personalized letter for each friend: describe the moment you met, funny experiences you shared, and the value they bring to your life. Put these letters in beautiful envelopes with their names on them. Look through old photos together and relive memories. Play a ''best moment'' game: everyone shares the group''s best memory. Prepare small but meaningful gifts for each other — set a budget limit so no one feels pressured. Create a friendship capsule: have everyone write a wish and a memory in a jar, sealed to be opened one year later. Take a group photo and have it framed. Make this day an annual tradition. Remember, friendship requires nurturing — this special day is the most beautiful expression of that care.'
WHERE slug = 'friendship-appreciation-day';

-- 8. beach-proposal
UPDATE public.scenarios SET
  description_tr = 'Sahilde evlilik teklifi, denizin büyüsünü aşkınızla birleştiren romantik bir andır. İlk adım olarak tenha ve güzel manzaralı bir sahil seçin; kalabalık plajlardan kaçının. Gün batımı saatini tam olarak kontrol edin ve en az bir saat öncesinden sahilde olun. Kumda büyük harflerle partnerinizin adını ve ''Benimle evlenir misin?'' yazısını hazırlayın. Yazının etrafına deniz kabukları ve cam fenerler içine yerleştirilmiş mumlar dizin — rüzgâra karşı korunaklı mumlar tercih edin. Bir battaniye serin, üzerine gül yaprakları serpin. Şampanya, iki kadeh ve çilek hazırlayın. Gizli fotoğrafçı tutun: kayalıkların arkasına veya uzak bir noktaya yerleşsin, telefoto lensle çeksin. Partnerinizi ''sahilde yürüyüş yapalım'' diyerek doğal bir şekilde getirin. O büyülü anda diz çökün, gözlerinin içine bakarak en içten duygularınızı paylaşın. Yüzüğü çıkarırken ellerinizin titremesi normaldir — bu anın güzelliğinin bir parçası. ''Evet'' dedikten sonra deniz kenarında birlikte dans edin. Mendil ve yedek pil getirmeyi unutmayın!',
  description_en = 'A beach proposal is a romantic moment that combines the magic of the sea with your love. As the first step, choose a secluded beach with a beautiful view; avoid crowded beaches. Check the exact sunset time and arrive at the beach at least an hour early. Write your partner''s name and ''Will you marry me?'' in large letters in the sand. Around the message, arrange seashells and candles placed inside glass lanterns — choose wind-resistant candles. Lay out a blanket and sprinkle rose petals on it. Prepare champagne, two glasses, and strawberries. Hire a secret photographer: position them behind rocks or at a distant point to shoot with a telephoto lens. Bring your partner naturally by saying ''let''s walk on the beach.'' At that magical moment, get on one knee, look into their eyes, and share your most heartfelt feelings. Your hands trembling as you pull out the ring is normal — it''s part of the beauty of this moment. After they say ''yes,'' dance together by the sea. Don''t forget to bring tissues and spare batteries!'
WHERE slug = 'beach-proposal';

-- 9. candlelight-dinner
UPDATE public.scenarios SET
  description_tr = 'Mum ışığında akşam yemeği, romantizmin en klasik ve etkileyici ifadelerinden biridir. Evde hazırlamak isterseniz, partneriniz dışarıdayken tüm hazırlığı tamamlayın. Yemek masasını beyaz veya krem örtüyle kaplayın, ortaya farklı boy mumlar yerleştirin. Porselen tabak, kristal kadeh ve gümüş çatal bıçak takımı kullanın — detaylar önemlidir. Masaya taze çiçek düzenlemesi koyun, gül veya şakayık zarif durur. Üç çeşit yemek hazırlayın: başlangıç olarak bruschetta veya çorba, ana yemek olarak biftek veya somon, tatlı olarak çikolatalı sufle. Yemek yapmakta zorlanıyorsanız kaliteli bir restorandan paket sipariş edip güzelce tabağa dizin — kimse farketmez. Işıkları tamamen kapatın, sadece mum ışığı olsun. Romantik bir playlist çalın: Frank Sinatra, Norah Jones veya Türk sanat müziği. Telefonları sessiz modda başka odaya bırakın. Yemek sırasında birbirinize anlamlı sorular sorun: ''Birlikte en mutlu olduğun an hangisiydi?'' gibi. Gecenin sonunda birlikte dans edin — mutfağın ortasında bile olsa büyülü olacaktır.',
  description_en = 'A candlelight dinner is one of the most classic and impressive expressions of romance. If preparing at home, complete all preparations while your partner is away. Cover the dining table with a white or cream cloth, and place candles of different heights in the center. Use porcelain plates, crystal glasses, and silver cutlery — details matter. Place a fresh flower arrangement on the table; roses or peonies look elegant. Prepare a three-course meal: bruschetta or soup as a starter, steak or salmon as the main course, chocolate souffle for dessert. If cooking is challenging, order from a quality restaurant and plate it beautifully — no one will notice. Turn off all lights completely, using only candlelight. Play a romantic playlist: Frank Sinatra, Norah Jones, or classical music. Leave phones on silent in another room. During dinner, ask each other meaningful questions like ''What was your happiest moment together?'' At the end of the evening, dance together — even in the middle of the kitchen, it will be magical.'
WHERE slug = 'candlelight-dinner';

-- 10. surprise-weekend-getaway
UPDATE public.scenarios SET
  description_tr = 'Sürpriz hafta sonu kaçamağı, rutinden kaçıp partnerinizle özel anılar biriktirmenin en heyecanlı yoludur. Gizlice bir plan yapın: partnerinizin takviminin boş olduğu bir hafta sonu seçin ve işten izin alması gerekiyorsa bunu ayarlayın. Varış noktasını tamamen sürpriz tutun — ''Bavulunu hazırla, gerisini bana bırak'' deyin. Rahat kıyafetler, mayo, şarj aleti ve temel ihtiyaçları içeren bir kontrol listesi hazırlayın. Dağ evi, butik otel, termal tesis veya sahil kasabası gibi bir yer seçin. Yolculuğu eğlenceli hale getirin: araba için özel bir playlist hazırlayın, yol boyunca küçük ipuçları verin. Varışta odada sürpriz bir düzenleme olsun: çiçekler, çikolata, el yazısı bir mektup. Programı önceden planlayın ama esnek bırakın: doğa yürüyüşü, yerel restoranlarda yemek, gün batımı izleme, spa. Sabah kahvaltısını yatakta hazırlayın veya yerel bir kafede keşif yapın. Fotoğraf makinesi getirin, her anı ölümsüzleştirin. Dönüşte partnerinize küçük bir hatıra hediye alın — bir magnet veya yerel el yapımı bir aksesuar. Bu kaçamağı yıllık gelenek haline getirin.',
  description_en = 'A surprise weekend getaway is the most exciting way to escape routine and create special memories with your partner. Make a secret plan: choose a weekend when your partner''s calendar is clear and arrange time off from work if needed. Keep the destination a complete surprise — say ''Pack your bag and leave the rest to me.'' Prepare a checklist with comfortable clothes, swimwear, charger, and essentials. Choose a destination like a mountain cabin, boutique hotel, thermal resort, or coastal town. Make the journey fun: prepare a special playlist for the car and give small hints along the way. Have a surprise arrangement in the room upon arrival: flowers, chocolate, a handwritten letter. Plan the itinerary in advance but keep it flexible: nature walks, dining at local restaurants, watching the sunset, spa. Prepare breakfast in bed or explore a local cafe in the morning. Bring a camera and capture every moment. On the way back, buy your partner a small souvenir — a magnet or a locally handmade accessory. Make this getaway an annual tradition.'
WHERE slug = 'surprise-weekend-getaway';

-- 11. valentines-scavenger-hunt
UPDATE public.scenarios SET
  description_tr = 'Sevgililer Günü hazine avı, romantizmi macera ile birleştiren yaratıcı bir sürprizdir. Bir hafta öncesinden planlamaya başlayın: beş ile on ipucu noktası belirleyin. Her ipucu, ilişkinizle ilgili özel bir anıya referans versin — ''İlk öpüştüğümüz yere git'' veya ''Sana ilk çiçeği aldığım dükkânı bul'' gibi. İpuçlarını küçük zarflara koyun, her zarfın üzerine bir kalp ve sıra numarası yapıştırın. İlk ipucunu sabah yastığının altına veya kahve fincanının yanına bırakın. Her durakta küçük bir hediye olsun: çikolata, tek bir gül, el yazısı bir not, favori parfümünün küçük şişesi. Son durak en özel olmalıdır — romantik bir akşam yemeği hazırlanmış bir masa, bir takı kutusu veya birlikte izleyeceğiniz bir konser bileti. İpuçlarını şifreli veya tekerlemeli yazarsanız daha eğlenceli olur. Güzergâhı mantıklı sıralayın, gereksiz uzun yürüyüşlerden kaçının. Her noktada fotoğraf çekin. Partneriniz zorlanırsa yardımcı ipuçları verin. Bu avın sonunda birlikte geçirdiğiniz tüm güzel anıları yeniden yaşamış olacaksınız.',
  description_en = 'A Valentine''s Day scavenger hunt is a creative surprise that combines romance with adventure. Start planning a week in advance: determine five to ten clue locations. Each clue should reference a special memory from your relationship — like ''Go to where we first kissed'' or ''Find the shop where I bought you your first flowers.'' Place clues in small envelopes with a heart and sequence number on each. Leave the first clue under the pillow in the morning or beside the coffee cup. Have a small gift at each stop: chocolate, a single rose, a handwritten note, a small bottle of their favorite perfume. The final stop should be the most special — a table set for a romantic dinner, a jewelry box, or concert tickets for a show to attend together. Writing clues in code or riddles makes it more fun. Plan the route logically and avoid unnecessarily long walks. Take photos at each location. If your partner struggles, provide helper hints. By the end of this hunt, you will have relived all the beautiful moments you shared together.'
WHERE slug = 'valentines-scavenger-hunt';

-- 12. midnight-birthday-surprise
UPDATE public.scenarios SET
  description_tr = 'Gece yarısı doğum günü sürprizi, sevdiğiniz kişinin yeni yaşını ilk kutlayan siz olmanızı sağlayan unutulmaz bir andır. Birkaç gün öncesinden hazırlığa başlayın: pasta siparişi verin veya kendiniz pişirin, mumları ve çakmağı hazırlayın. Odayı gizlice süsleyin — doğum günü kişisi uyuduktan sonra balonlar, konfeti ve ''İyi ki doğdun'' pankartı asın. Hediyeyi özenle paketleyin ve el yazısıyla kişisel bir kart yazın. Gece 23:50''de alarm kurun, süslemeye başlayın. Saat tam 00:00''da pastayı mumları yanmış şekilde taşıyarak odaya girin, ''İyi ki doğdun'' şarkısını söyleyin. Uykulu gözlerle şaşkınlıkla bakan yüzü paha biçilmezdir. Mumları üfledikten sonra ilk dileklerini sorsanız bile saklasınlar — gelenek böyle! Küçük bir gece yarısı sofrası kurun: favori atıştırmalıklar, pasta ve sıcak içecek. O anı çekmek için telefonu önceden hazırlayın. Eğer partnerinizse, ''Seninle uyandığım her gün doğum günüm gibi'' gibi romantik bir cümle söyleyin. Bu sürpriz, basit ama yürekten geldiği için en çok hatırlananlardandır.',
  description_en = 'A midnight birthday surprise is an unforgettable moment that ensures you are the first to celebrate your loved one''s new year. Start preparing a few days in advance: order a cake or bake one yourself, and prepare candles and a lighter. Secretly decorate the room — after the birthday person falls asleep, hang balloons, confetti, and a ''Happy Birthday'' banner. Carefully wrap the gift and write a personal card by hand. Set an alarm for 11:50 PM and begin decorating. At exactly midnight, walk into the room carrying the cake with lit candles, singing ''Happy Birthday.'' The look of sleepy-eyed surprise on their face is priceless. After they blow out the candles, even if you ask for their first wish, they should keep it secret — that is the tradition! Set up a small midnight table: favorite snacks, cake, and a warm drink. Have your phone ready beforehand to capture the moment. If it is your partner, say something romantic like ''Every day I wake up next to you feels like my birthday.'' This surprise is among the most remembered because it is simple yet comes from the heart.'
WHERE slug = 'midnight-birthday-surprise';

-- 13. surprise-road-trip
UPDATE public.scenarios SET
  description_tr = 'Sürpriz yol gezisi, spontanlığın ve maceranın tadını çıkarmanın en güzel yollarından biridir. Öncelikle aracınızın bakımını yaptırın: lastik basıncı, yağ, cam suyu ve fren kontrolü önemlidir. Güzergâhı gizlice planlayın ama alternatif rotalar da hazırlayın. Partnerinize veya arkadaşlarınıza sadece ''Yarın sabah hazır ol, rahat giyin'' deyin — detay vermeyin. Araba için özel bir playlist hazırlayın: yolculuk şarkıları, eski favoriler ve birlikte söyleyeceğiniz düetler. Yol boyunca eğlenceli duraklar planlayın: yerel bir kahvaltıcı, manzara noktası, küçük kasaba gezisi veya çiftlik ziyareti. Araçta atıştırmalık çantası hazırlayın: sandviçler, meyve, kuruyemiş ve bol su. Yolda oyunlar oynayın: plaka oyunu, yirmi soru veya ''ya şunu ya bunu'' gibi. Fotoğraf makinesi veya polaroid getirin, spontan anları yakalayın. Varış noktasında bir sürpriz beklesin: daha önce hiç gitmedikleri bir restoran, gizli bir plaj veya panoramik bir tepe. Dönüş yolunu farklı bir güzergâhtan yapın. Bu yolculuğun güzelliği, varış noktası değil birlikte geçirilen yoldadır.',
  description_en = 'A surprise road trip is one of the most beautiful ways to enjoy spontaneity and adventure. First, have your vehicle serviced: tire pressure, oil, windshield fluid, and brake checks are important. Secretly plan the route but also prepare alternative paths. Tell your partner or friends only ''Be ready tomorrow morning, dress comfortably'' — give no details. Prepare a special playlist for the car: road trip songs, old favorites, and duets to sing together. Plan fun stops along the way: a local breakfast spot, a scenic viewpoint, a small-town tour, or a farm visit. Pack a snack bag for the car: sandwiches, fruit, nuts, and plenty of water. Play games on the road: the license plate game, twenty questions, or ''would you rather.'' Bring a camera or Polaroid to capture spontaneous moments. Have a surprise waiting at the destination: a restaurant they have never been to, a hidden beach, or a panoramic hilltop. Take a different route on the way back. The beauty of this trip is not the destination but the journey shared together.'
WHERE slug = 'surprise-road-trip';

-- 14. restaurant-proposal
UPDATE public.scenarios SET
  description_tr = 'Restoranda evlilik teklifi, şıklık ve sürprizin bir arada sunulduğu klasik ama her zaman etkili bir andır. En az iki hafta öncesinden restoran araştırmasına başlayın: özel oda veya balkon masası olan, sessiz ve romantik bir yer seçin. Restoran yöneticisiyle planınızı gizlice paylaşın — çoğu restoran bu tür sürprizlere çok alışkındır. Yüzüğün nasıl sunulacağını kararlaştırın: tatlının içinde, kadeh yanında veya garsonun getireceği özel bir kutuda. Masaya önceden çiçek ve mum yerleştirtin. Özel bir menü hazırlattırabilirsiniz: partnerinizin en sevdiği yemeklerden oluşan bir sıralama. Akşam için özenle giyinin, partnerinize de ''özel bir yere gidiyoruz'' deyin ki o da şık giyinsin. Yemek boyunca sakin olun, birlikte yaşadığınız güzel anıları konuşun. Tatlı servisiyle birlikte yüzük geldiğinde diz çökün ve kalbinizden geçenleri söyleyin. Uzun ezberlenmiş konuşmalar yerine samimi birkaç cümle çok daha etkilidir. ''Evet'' cevabından sonra şampanyayla kadeh kaldırın. Restoran personelinden tebrik ve alkış beklemeyi unutmayın — anı taçlandırırlar.',
  description_en = 'A restaurant proposal is a classic yet always effective moment where elegance and surprise come together. Start researching restaurants at least two weeks in advance: choose a quiet, romantic place with a private room or balcony table. Secretly share your plan with the restaurant manager — most restaurants are very experienced with such surprises. Decide how the ring will be presented: inside the dessert, beside the glass, or in a special box brought by the waiter. Have flowers and candles placed on the table beforehand. You can have a special menu prepared: a sequence of your partner''s favorite dishes. Dress carefully for the evening and tell your partner ''we are going somewhere special'' so they dress up too. Stay calm during dinner and talk about beautiful moments you have shared together. When the ring arrives with the dessert, get on one knee and say what is in your heart. A few sincere sentences are far more powerful than long memorized speeches. After the ''yes,'' raise a toast with champagne. Expect congratulations and applause from the restaurant staff — they will crown the moment.'
WHERE slug = 'restaurant-proposal';

-- 15. stargazing-night
UPDATE public.scenarios SET
  description_tr = 'Yıldız izleme gecesi, şehrin ışıklarından uzakta gökyüzünün büyüsüne kendinizi bırakmanın en huzurlu yoludur. Öncelikle hava durumunu kontrol edin: bulutsuz ve ay ışığının az olduğu bir gece seçin. Şehir dışında karanlık bir alan bulun — çiftlik arazisi, tepe üstü veya göl kenarı idealdir. Kalın bir battaniye veya kamp matı getirin, üzerine yastıklar koyun. Dürbün veya küçük bir teleskop harika olur ama çıplak gözle bile gökyüzü muhteşemdir. Yıldız haritası uygulaması indirin (Star Walk veya SkyView gibi) — takımyıldızları birlikte keşfedin. Termos içinde sıcak çikolata veya bitki çayı, yanında kurabiye getirin. Bluetooth hoparlörle çok kısık sakin müzik çalın veya doğanın seslerini dinleyin. Birbirinize sorular sorun: ''Evrende başka hayat olsa nasıl olurdu?'' veya ''Çocukken ne olmak istiyordun?'' Kayan yıldız görürseniz dilek tutun. Cep telefonlarının ekran parlaklığını en düşüğe ayarlayın ki gece görüşünüz bozulmasın. Geri dönüş yolu için el feneri getirin. Bu gece, hayatın koşuşturmasından bir adım geri çekilip evrenin büyüklüğünü hissetmenizi sağlayacak.',
  description_en = 'A stargazing night is the most peaceful way to surrender yourself to the magic of the sky, away from city lights. First, check the weather: choose a cloudless night with minimal moonlight. Find a dark area outside the city — farmland, a hilltop, or a lakeside is ideal. Bring a thick blanket or camping mat and place pillows on it. Binoculars or a small telescope would be wonderful, but the sky is magnificent even with the naked eye. Download a star map app (like Star Walk or SkyView) and discover constellations together. Bring hot chocolate or herbal tea in a thermos, along with cookies. Play very soft calm music on a Bluetooth speaker or just listen to nature''s sounds. Ask each other questions: ''What would it be like if there were other life in the universe?'' or ''What did you want to be when you were a child?'' If you see a shooting star, make a wish. Set phone screen brightness to the lowest so your night vision is not disturbed. Bring a flashlight for the way back. This night will let you step back from life''s hustle and feel the vastness of the universe.'
WHERE slug = 'stargazing-night';

-- 16. heartfelt-apology
UPDATE public.scenarios SET
  description_tr = 'İçten bir özür dileme, ilişkilerdeki kırılmaları onarmak ve güveni yeniden inşa etmek için cesaret isteyen ama çok değerli bir adımdır. Öncelikle ne için özür dilediğinizi net olarak anlayın — ''üzgünüm'' demek yetmez, hatanızı somut olarak ifade edin. Sessiz ve rahat bir ortam seçin: ev, sakin bir park veya tanıdık bir kafe. Karşı tarafın konuşmaya hazır olduğundan emin olun, zorlamayın. Yüz yüze konuşun, mesaj veya telefon yetersiz kalır. Konuşmanıza şöyle başlayın: ''Sana ... konusunda yanlış davrandım ve bunun seni nasıl hissettirdiğini anlıyorum.'' Bahaneler üretmeyin, savunmaya geçmeyin. Karşı tarafı dinleyin, sözünü kesmeyin, duygularını geçersiz kılmayın. ''Haklısın'' demeyi bilin. Somut bir değişim planı sunun: ''Bundan sonra ... yapacağım'' gibi. Küçük ama anlamlı bir jest yapın: el yazısı bir mektup, favori çiçekleri veya anlamlı bir hediye. Unutmayın, özür bir kez söylenir ama değişim sürekli gösterilir. Sabırlı olun — güven inşası zaman alır. Karşı tarafın affetmeye hazır olması için baskı yapmayın, alan tanıyın.',
  description_en = 'A heartfelt apology is a courageous yet invaluable step to repair relationship fractures and rebuild trust. First, clearly understand what you are apologizing for — saying ''sorry'' is not enough, you must express your mistake concretely. Choose a quiet, comfortable setting: home, a peaceful park, or a familiar cafe. Make sure the other person is ready to talk, and do not force it. Speak face to face; messages or phone calls fall short. Begin your conversation with: ''I was wrong about ... and I understand how it made you feel.'' Do not make excuses and do not become defensive. Listen to the other person, do not interrupt, and do not invalidate their feelings. Know when to say ''You are right.'' Offer a concrete plan for change: ''From now on, I will ...'' Make a small but meaningful gesture: a handwritten letter, their favorite flowers, or a meaningful gift. Remember, an apology is said once but change must be shown continuously. Be patient — rebuilding trust takes time. Do not pressure the other person to forgive; give them space.'
WHERE slug = 'heartfelt-apology';

-- 17. picnic-in-the-park
UPDATE public.scenarios SET
  description_tr = 'Parkta piknik, doğanın içinde sevdiklerinizle kaliteli vakit geçirmenin en keyifli ve bütçe dostu yollarından biridir. Hava durumunu birkaç gün öncesinden takip edin ve güneşli bir gün seçin. Gölgelik ağaçların altında veya göl kenarında güzel bir nokta belirleyin. Büyük bir piknik battaniyesi veya örtüsü getirin, yastıklar da rahatlık katar. Piknik sepeti hazırlayın: sandviçler, börek, meyve tabağı, peynir ve zeytin tabağı, ev yapımı limonata, kurabiye. Tabak, bardak ve peçete unutmayın — cam yerine plastik veya bambu tercih edin. Bluetooth hoparlörle hafif müzik çalın. Aktiviteler planlayın: frisbee, kart oyunları, badminton veya birlikte kitap okuma. Çiçek tarlası varsa fotoğraf çekin. Battaniyeye uzanıp bulutlarda şekil arayın — çocukluğunuza dönün. Güneş kremi ve böcek kovucu getirin. Çöplerinizi toplayın ve parkı temiz bırakın. Akşamüstüne doğru gün batımını izleyin. Bu basit ama samimi an, en pahalı restoran yemeğinden daha değerli anılar bırakır. Pikniği düzenli hale getirin — ayda bir ''piknik günümüz'' olsun.',
  description_en = 'A picnic in the park is one of the most enjoyable and budget-friendly ways to spend quality time with your loved ones in nature. Track the weather a few days in advance and choose a sunny day. Find a beautiful spot under shady trees or by the lake. Bring a large picnic blanket or cloth; pillows add extra comfort. Prepare a picnic basket: sandwiches, pastries, a fruit platter, a cheese and olive board, homemade lemonade, and cookies. Don''t forget plates, cups, and napkins — choose plastic or bamboo instead of glass. Play light music on a Bluetooth speaker. Plan activities: frisbee, card games, badminton, or reading books together. If there is a flower field, take photos. Lie on the blanket and search for shapes in the clouds — return to your childhood. Bring sunscreen and bug spray. Collect your trash and leave the park clean. Watch the sunset in the late afternoon. This simple yet sincere moment leaves more valuable memories than the most expensive restaurant dinner. Make picnics a regular thing — have a ''picnic day'' once a month.'
WHERE slug = 'picnic-in-the-park';

-- 18. new-year-surprise
UPDATE public.scenarios SET
  description_tr = 'Yılbaşı sürprizi, eski yılı güzel anılarla uğurlayıp yeni yıla umutla başlamanın en özel yoludur. Bir hafta öncesinden hazırlığa başlayın: evi ışık zincirleri, kar tanesi süsleri ve yılbaşı ağacıyla donatın. Gece için özel bir menü planlayın: hindi veya kuzu tandır, yan tabaklar ve özel bir tatlı. Gece yarısı için havai fişek veya maytap temin edin — balkon veya bahçede güvenli bir şekilde kullanın. Her misafir için küçük sürpriz hediyeler hazırlayın ve ağacın altına koyun. Gece yarısına sayarken herkesin elinde bir kadeh olsun. Yeni yıl dileklerini küçük kağıtlara yazıp bir kavanoza atın — gelecek yılbaşında açmak üzere saklayın. Geçen yılın en güzel anlarını anlatan bir slayt gösterisi hazırlayın. Konfeti ve parti düdüğü hazırlayın. Soğuk havalarda dışarı çıkacaksanız sıcak çorba veya salep ikram edin. Fotoğraf köşesi kurun: komik şapkalar, gözlükler ve yılbaşı temalı aksesuarlar. İlk dakikalarda sevdiklerinize sarılın, gözlerine bakarak ''Seninle bir yıl daha'' deyin. Bu gece, birlikteliğin kutlamasıdır.',
  description_en = 'A New Year''s surprise is the most special way to bid farewell to the old year with beautiful memories and welcome the new year with hope. Start preparing a week in advance: decorate the home with string lights, snowflake ornaments, and a Christmas tree. Plan a special menu for the evening: turkey or lamb roast, side dishes, and a special dessert. Get fireworks or sparklers for midnight — use them safely on a balcony or in the garden. Prepare small surprise gifts for each guest and place them under the tree. As you count down to midnight, make sure everyone has a glass in hand. Write new year wishes on small pieces of paper and drop them in a jar — save them to open next New Year''s. Prepare a slideshow of the past year''s best moments. Have confetti and party horns ready. If going outside in cold weather, serve warm soup or hot drinks. Set up a photo booth with funny hats, glasses, and New Year-themed accessories. In the first minutes, hug your loved ones, look into their eyes and say ''Another year with you.'' This night is a celebration of togetherness.'
WHERE slug = 'new-year-surprise';

-- 19. memory-lane-anniversary
UPDATE public.scenarios SET
  description_tr = 'Anı yolu yıldönümü, ilişkinizin en güzel anlarını yeniden yaşayarak kutlamanın derin ve duygusal bir yoludur. Birkaç hafta öncesinden hazırlığa başlayın: birlikte çektiğiniz tüm fotoğrafları kronolojik sırayla derleyin. İlk buluşma, ilk tatil, önemli dönüm noktaları gibi anları seçin. Her anı için kısa bir not yazın: ''Bu gün sahilde yağmura yakalanmıştık ve çok gülmüştük'' gibi. Fotoğrafları ip ve mandallarla bir duvara asın veya bir albüme yerleştirin. Evinizi ya da bir odayı bu anılarla donatın. Birlikte ilk gittiğiniz restoranda yemek yiyin veya ilk buluşma yerinizi ziyaret edin. Bir video montaj hazırlayın: fotoğraflar, video klipler ve arka planda ''şarkımız'' çalsın. El yazısıyla uzun bir mektup yazın: tanıştığınız günden bugüne hissettiklerinizi anlatın. Hediye olarak ilişkinizi temsil eden bir şey seçin: koordinat bilekliği, yıldız haritası veya özel bir çerçeve. Akşam mum ışığında yemek yiyin ve birbirinize ''Gelecek yıl birlikte ne yapmak istiyorsun?'' diye sorun. Bu gece geçmişe saygı, bugüne şükür ve geleceğe umuttur.',
  description_en = 'A memory lane anniversary is a deeply emotional way to celebrate by reliving the most beautiful moments of your relationship. Start preparing a few weeks in advance: compile all your photos together in chronological order. Select moments like your first date, first vacation, and important milestones. Write a short note for each memory: ''This was the day we got caught in the rain at the beach and laughed so much.'' Hang photos on a wall with string and clothespins or place them in an album. Decorate your home or a room with these memories. Eat at the restaurant you first went to together or visit your first date location. Prepare a video montage: photos, video clips, and ''our song'' playing in the background. Write a long letter by hand: describe your feelings from the day you met to today. Choose a gift that represents your relationship: a coordinate bracelet, star map, or special frame. Have dinner by candlelight in the evening and ask each other ''What do you want to do together next year?'' This night is respect for the past, gratitude for the present, and hope for the future.'
WHERE slug = 'memory-lane-anniversary';

-- 20. hot-air-balloon-ride
UPDATE public.scenarios SET
  description_tr = 'Sıcak hava balonu gezisi, gökyüzünden dünyaya bakarak unutulmaz bir deneyim yaşamanın en büyüleyici yoludur. En az üç hafta öncesinden araştırmaya başlayın: bölgenizdeki güvenilir balon firmalarını karşılaştırın, yorumları okuyun ve güvenlik sertifikalarını kontrol edin. Uçuşlar genellikle gün doğumunda yapılır, bu yüzden erken kalkmaya hazır olun. Hava koşullarına bağlı olarak iptal olabilir — esnek bir tarih planlayın. Rahat ve katmanlı giyinin: sabah erken saatlerde serin olur ama balon yükseldikçe güneş ısıtır. Yükseklik korkusu olanlar için balon sepetleri oldukça güvenlidir ve sallanma hissi minimumdur. Fotoğraf makinesi şarjını tam doldurun, yedek hafıza kartı getirin — manzaralar nefes kesici olacak. Uçuş sırasında pilot bilgi verir, sorular sorun. Balondan çıkış geleneksel olarak şampanya ile kutlanır. Bu deneyimi özel kılmak için özel uçuş seçin (sadece ikiniz ve pilot). Uçuş sonrası yakındaki bir köy kahvaltıcısında geleneksel kahvaltı yapın. Bu deneyim, ayakları yere basmayan mutluluğun en güzel kanıtıdır.',
  description_en = 'A hot air balloon ride is the most enchanting way to experience an unforgettable adventure viewing the world from the sky. Start researching at least three weeks in advance: compare reliable balloon companies in your region, read reviews, and check safety certifications. Flights typically take place at sunrise, so be prepared to wake up early. Flights may be cancelled depending on weather conditions — plan a flexible date. Dress comfortably in layers: early morning hours are cool but the sun warms as the balloon rises. For those with a fear of heights, balloon baskets are quite safe and the swaying sensation is minimal. Fully charge your camera and bring an extra memory card — the views will be breathtaking. During the flight, the pilot provides information, so ask questions. The landing is traditionally celebrated with champagne. To make this experience special, choose a private flight (just the two of you and the pilot). After the flight, have a traditional breakfast at a nearby village cafe. This experience is the most beautiful proof that happiness does not need to keep its feet on the ground.'
WHERE slug = 'hot-air-balloon-ride';

-- 21. random-act-of-kindness
UPDATE public.scenarios SET
  description_tr = 'Rastgele iyilik yapma, hem başkalarının hem de kendi gününüzü aydınlatmanın en saf ve güzel yoludur. Bir gün ayırın ve bilinçli olarak iyilik yapmayı hedefleyin. Sabah bir kafede arkadaki kişinin kahvesini ödeyin — onların şaşkın gülümsemesi güne harika başlamanızı sağlar. Komşunuza kapınıza bırakacağınız ev yapımı kurabiye veya çiçek götürün. Parkta çöp toplayın veya sokak hayvanlarını besleyin. Yaşlı bir komşunuzun market alışverişine yardım edin. Sosyal medyada tanımadığınız birinin işini veya sanatını destekleyen bir yorum bırakın. Bir kitap okuyup bitirdiyseniz, içine güzel bir not yazıp bir bankın üzerine bırakın — birisi onu bulduğunda mutlu olacaktır. Bir hayır kurumuna küçük bir bağış yapın. Otobüste yerinizi verin, markette sıranızı bırakın. İş arkadaşınıza masasına küçük bir not bırakın: ''Bugün harika iş çıkardın!'' Bu iyilikler küçük görünür ama domino etkisi yaratır. Akşam yaptığınız iyilikleri bir günlüğe yazın — bu alışkanlığı sürdürmek inanılmaz tatmin verici.',
  description_en = 'Random acts of kindness are the purest and most beautiful way to brighten both others'' and your own day. Set aside a day and consciously aim to do good deeds. In the morning, pay for the coffee of the person behind you at a cafe — their surprised smile will give you a wonderful start to the day. Bring homemade cookies or flowers to leave at your neighbor''s door. Pick up litter in the park or feed stray animals. Help an elderly neighbor with their grocery shopping. Leave a supportive comment on a stranger''s work or art on social media. If you have finished reading a book, write a nice note inside and leave it on a bench — someone will be happy when they find it. Make a small donation to a charity. Give up your seat on the bus or let someone go ahead in line at the store. Leave a small note on a colleague''s desk: ''You did amazing work today!'' These kindnesses seem small but create a domino effect. In the evening, write down the kind things you did in a journal — maintaining this habit is incredibly fulfilling.'
WHERE slug = 'random-act-of-kindness';

-- 22. birthday-treasure-hunt
UPDATE public.scenarios SET
  description_tr = 'Doğum günü hazine avı, sıradan bir hediye verme anını heyecanlı bir maceraya dönüştürmenin en yaratıcı yoludur. Bir gün öncesinden altı ile on ipucu hazırlayın, her biri bir sonraki ipucunun yerini göstersin. İpuçlarını bulmaca, şifre veya tekerleme şeklinde yazın: ''Acıktığında ilk baktığın yer'' (buzdolabı) veya ''Hayallerini gördüğün yere bak'' (yastık altı) gibi. Her ipucu noktasına küçük bir sürpriz bırakın: çikolata, balon, fotoğraf veya kısa bir el yazısı not. Ev dışına da yayılabilirsiniz: arabanın torpido gözü, posta kutusu veya favori kafesi. Son ipucu büyük hediyeye götürsün — güzelce paketlenmiş, balonlarla süslenmiş bir köşede olsun. İpuçlarını renkli kartlara yazın ve zarflara koyun, üstüne sıra numarası yapıştırın. Doğum günü kişisi zorlanırsa ''sıcak-soğuk'' yöntemiyle yardımcı olun. Tüm avı videoya çekin — tepkileri paha biçilmezdir. Grup halinde yapıyorsanız takımlar oluşturun ve yarış havasına sokun. Bu hazine avı, hediyenin kendisi kadar hediyeye ulaşma yolculuğunu da unutulmaz kılar.',
  description_en = 'A birthday treasure hunt is the most creative way to transform an ordinary gift-giving moment into an exciting adventure. Prepare six to ten clues the day before, each pointing to the location of the next clue. Write clues as puzzles, codes, or riddles: ''The first place you look when hungry'' (refrigerator) or ''Look where you see your dreams'' (under the pillow). Leave a small surprise at each clue location: chocolate, a balloon, a photo, or a short handwritten note. You can extend beyond the house: the car''s glove compartment, the mailbox, or their favorite cafe. The final clue should lead to the big gift — beautifully wrapped in a corner decorated with balloons. Write clues on colorful cards and place them in envelopes with sequence numbers. If the birthday person struggles, help them using the ''hot-cold'' method. Record the entire hunt on video — the reactions are priceless. If doing this as a group, form teams and make it a race. This treasure hunt makes the journey to the gift just as unforgettable as the gift itself.'
WHERE slug = 'birthday-treasure-hunt';

-- 23. rooftop-proposal
UPDATE public.scenarios SET
  description_tr = 'Çatıda evlilik teklifi, şehrin ışıklarını ve gökyüzünü sahne olarak kullanan nefes kesici bir andır. Öncelikle güvenli ve yasal erişimi olan bir çatı veya teras bulun: otellerin çatı katı restoranları, rooftop barlar veya bir arkadaşınızın apartman terası olabilir. İzin almayı unutmayın. Çatıyı romantik bir şekilde süsleyin: yere led mumlar veya peri ışıkları dizin, bir yol oluşturarak bir noktaya yönlendirin. O noktaya çiçek düzenlemesi, ''Benimle evlenir misin?'' pankartı ve şampanya masası yerleştirin. Müzik için Bluetooth hoparlör kullanın — partnerinizin en sevdiği romantik şarkıyı çalın. Gizli fotoğrafçı veya videograf tutun; çatıda saklanacak bir yer bulması gerekir. Partnerinizi çatıya getirmek için ''Bir arkadaşın sürpriz partisi var'' veya ''Manzarayı görmek ister misin?'' gibi bahaneler kullanın. Merdivenlerden çıkarken heyecanınızı kontrol edin. Çatıya adım attığında süslemeleri görüp şaşırdığı anda diz çökün. Şehrin ışıkları altında kalbinizi açın. Rüzgârlı olabilir — hafif bir şal veya ceket getirin. Yükseklik korkusu varsa kenardan uzak durun. Bu an, dünyanın tepesinde aşkınızı ilan etmektir.',
  description_en = 'A rooftop proposal is a breathtaking moment that uses the city lights and the sky as your stage. First, find a rooftop or terrace with safe and legal access: it could be a hotel rooftop restaurant, a rooftop bar, or a friend''s apartment terrace. Don''t forget to get permission. Decorate the rooftop romantically: line the floor with LED candles or fairy lights, creating a path that leads to one spot. At that spot, place a flower arrangement, a ''Will you marry me?'' banner, and a champagne table. Use a Bluetooth speaker for music — play your partner''s favorite romantic song. Hire a hidden photographer or videographer; they will need to find a hiding spot on the roof. Use excuses to bring your partner to the rooftop like ''A friend has a surprise party'' or ''Want to see the view?'' Control your excitement while climbing the stairs. The moment they step onto the roof and see the decorations in surprise, get on one knee. Open your heart under the city lights. It can be windy — bring a light shawl or jacket. If there is a fear of heights, stay away from the edge. This moment is declaring your love on top of the world.'
WHERE slug = 'rooftop-proposal';
